// src/pages/BuildPC.jsx
import React, { useState } from "react";
import { useStore } from "../stores/useStore"; // Assuming useStore manages cart and PC build components
import BuildGif from "../assets/Pc Build .gif";
const BuildPC = () => {
  const [currentStep, setCurrentStep] = useState(0);
  const { buildPcComponents, setPcComponent, cart, addToCart } = useStore(); // Get cart and addToCart from store
  const [quantities, setQuantities] = useState({}); // Local state for quantities

  // State for pagination
  const [currentPage, setCurrentPage] = useState({}); // Use an object to track page per step

  // Tooltips for each step (now used in the modal)
  const stepInfoTexts = {
    cpu:
      "The CPU is the PC’s brain that handles calculations. It must match your motherboard’s CPU socket. Ensure it’s properly cooled for stable performance (use a good CPU cooler).",
    motherboard:
      "The motherboard connects all components in your PC. It must support your CPU’s socket and the right type of RAM. Also, check that the board’s size (ATX, mATX, etc.) fits your case.",
    ram:
      "RAM provides temporary storage for data the CPU needs quick access to. Ensure it's compatible with your motherboard's RAM type (DDR4, DDR5) and speed.",
    case:
      "The case houses all your components. Ensure it's compatible with your motherboard's form factor (ATX, Micro-ATX, etc.) and has enough space for your GPU and PSU.",
    "cpu-cooler":
      "A CPU cooler dissipates heat generated by the CPU. Choose one compatible with your CPU socket and fits within your case's clearance limits.",
    storage:
      "Storage devices hold your operating system, programs, and files. Choose between SSDs (faster) and HDDs (larger capacity). Ensure your motherboard has the necessary connections (SATA, M.2).",
    gpu:
      "The GPU processes graphics and video. It's essential for gaming and video editing. Ensure your PSU has enough power and your case has enough space.",
    psu:
      "The PSU supplies power to all components. Choose one with enough wattage for your build and good efficiency ratings (80+ Bronze, Gold, etc.).",
  };

  const steps = [
    { id: "cpu", name: "CPU", title: "Select CPU" },
    { id: "motherboard", name: "Motherboard", title: "Select Motherboard" },
    { id: "ram", name: "RAM", title: "Select RAM" },
    { id: "case", name: "Case", title: "Select Case" },
    { id: "cpu-cooler", name: "CPU Cooler", title: "Select CPU Cooler" },
    { id: "storage", name: "Storage", title: "Select Storage" },
    { id: "gpu", name: "GPU", title: "Select GPU" },
    { id: "psu", name: "PSU", title: "Select Power Supply" },
  ];

  // Mock components data with expanded specs (same as before)
  const mockComponents = {
    // ... (same data as in your previous file)
    cpu: [
      {
        id: 1,
        name: "Intel Core i9-13900K",
        price: 589,
        socket: "LGA1700",
        integratedGraphics: true,
        tdp: 125,
        image: "https://placehold.co/100x100?text=i9-13900K  ",
        supportedMemoryTypes: ["DDR4", "DDR5"],
        maxMemorySpeed: 5600,
        maxMemoryCapacity: 128,
      },
      {
        id: 2,
        name: "AMD Ryzen 9 7950X",
        price: 699,
        socket: "AM5",
        integratedGraphics: false,
        tdp: 170,
        image: "https://placehold.co/100x100?text=Ryzen+9+7950X  ",
        supportedMemoryTypes: ["DDR5"],
        maxMemorySpeed: 5200,
        maxMemoryCapacity: 128,
      },
      {
        id: 3,
        name: "Intel Core i7-13700K",
        price: 419,
        socket: "LGA1700",
        integratedGraphics: true,
        tdp: 125,
        image: "https://placehold.co/100x100?text=i7-13700K  ",
        supportedMemoryTypes: ["DDR4", "DDR5"],
        maxMemorySpeed: 5600,
        maxMemoryCapacity: 128,
      },
      // Add more CPU mock data as needed...
    ],
    motherboard: [
      {
        id: 1,
        name: "ASUS ROG Strix Z790-E",
        price: 350,
        socket: "LGA1700",
        formFactor: "ATX",
        memorySlots: 4,
        maxMemorySpeed: 5600,
        maxMemoryCapacity: 128,
        supportedMemoryTypes: ["DDR4", "DDR5"],
        storageSlots: { sata: 6, m2: 4 },
        pcieVersion: 5.0,
        image: "https://placehold.co/100x100?text=ROG+Strix+Z790-E  ",
      },
      {
        id: 2,
        name: "MSI MAG B650 Tomahawk",
        price: 180,
        socket: "AM5",
        formFactor: "ATX",
        memorySlots: 4,
        maxMemorySpeed: 6000,
        maxMemoryCapacity: 128,
        supportedMemoryTypes: ["DDR5"],
        storageSlots: { sata: 4, m2: 2 },
        pcieVersion: 5.0,
        image: "https://placehold.co/100x100?text=MAG+B650+Tomahawk  ",
      },
      {
        id: 3,
        name: "Gigabyte B660M DS3H",
        price: 100,
        socket: "LGA1700",
        formFactor: "Micro-ATX",
        memorySlots: 2,
        maxMemorySpeed: 3200,
        maxMemoryCapacity: 64,
        supportedMemoryTypes: ["DDR4"],
        storageSlots: { sata: 4, m2: 1 },
        pcieVersion: 4.0,
        image: "https://placehold.co/100x100?text=B660M+DS3H  ",
      },
      {
        id: 4,
        name: "ASRock B550M-HDV",
        price: 85,
        socket: "AM4",
        formFactor: "Micro-ATX",
        memorySlots: 2,
        maxMemorySpeed: 4400,
        maxMemoryCapacity: 128,
        supportedMemoryTypes: ["DDR4"],
        storageSlots: { sata: 4, m2: 1 },
        pcieVersion: 4.0,
        image: "https://placehold.co/100x100?text=B550M-HDV  ",
      },
      // Add more Motherboard mock data as needed...
    ],
    case: [
      {
        id: 1,
        name: "NZXT H510",
        price: 70,
        formFactor: "ATX",
        supportedFormFactors: ["ATX", "Micro-ATX", "Mini-ITX"],
        maxGpuLength: 360,
        maxCpuCoolerHeight: 160,
        color: "Black",
        image: "https://placehold.co/100x100?text=NZXT+H510  ",
      },
      {
        id: 2,
        name: "Fractal Design Meshify C",
        price: 90,
        formFactor: "ATX",
        supportedFormFactors: ["ATX", "Micro-ATX", "Mini-ITX"],
        maxGpuLength: 360,
        maxCpuCoolerHeight: 165,
        color: "White",
        image: "https://placehold.co/100x100?text=Meshify+C  ",
      },
      {
        id: 3,
        name: "Corsair 4000D Airflow",
        price: 100,
        formFactor: "ATX",
        supportedFormFactors: ["ATX", "Micro-ATX", "Mini-ITX"],
        maxGpuLength: 360,
        maxCpuCoolerHeight: 170,
        color: "Black",
        image: "https://placehold.co/100x100?text=4000D+Airflow  ",
      },
      {
        id: 4,
        name: "Fractal Design Core 1000",
        price: 50,
        formFactor: "Micro-ATX",
        supportedFormFactors: ["Micro-ATX", "Mini-ITX"],
        maxGpuLength: 300,
        maxCpuCoolerHeight: 160,
        color: "Black",
        image: "https://placehold.co/100x100?text=Core+1000  ",
      },
      // Add more Case mock data as needed...
    ],
    ram: [
      {
        id: 1,
        name: "Corsair Vengeance RGB 32GB",
        price: 120,
        size: "32GB",
        speed: "3200MHz",
        type: "DDR4",
        slotsUsed: 2,
        image: "https://placehold.co/100x100?text=Vengeance+32GB  ",
      },
      {
        id: 2,
        name: "G.Skill Trident Z5 16GB",
        price: 80,
        size: "16GB",
        speed: "3600MHz",
        type: "DDR5",
        slotsUsed: 2,
        image: "https://placehold.co/100x100?text=Trident+Z5+16GB  ",
      },
      {
        id: 3,
        name: "Crucial Ballistix 32GB",
        price: 110,
        size: "32GB",
        speed: "3000MHz",
        type: "DDR4",
        slotsUsed: 2,
        image: "https://placehold.co/100x100?text=Ballistix+32GB  ",
      },
      {
        id: 4,
        name: "Kingston Fury Beast 64GB",
        price: 200,
        size: "64GB",
        speed: "3200MHz",
        type: "DDR4",
        slotsUsed: 2,
        image: "https://placehold.co/100x100?text=Fury+Beast+64GB  ",
      },

      {
        id: 5,
        name: "Corsair Vengeance RGB 32GB",
        price: 120,
        size: "32GB",
        speed: "3200MHz",
        type: "DDR4",
        slotsUsed: 2,
        image: "https://placehold.co/100x100?text=Vengeance+32GB  ",
      },
      {
        id: 6,
        name: "G.Skill Trident Z5 16GB",
        price: 80,
        size: "16GB",
        speed: "3600MHz",
        type: "DDR5",
        slotsUsed: 2,
        image: "https://placehold.co/100x100?text=Trident+Z5+16GB  ",
      },
      {
        id: 7,
        name: "Crucial Ballistix 32GB",
        price: 110,
        size: "32GB",
        speed: "3000MHz",
        type: "DDR4",
        slotsUsed: 2,
        image: "https://placehold.co/100x100?text=Ballistix+32GB  ",
      },
      {
        id: 8,
        name: "Kingston Fury Beast 64GB",
        price: 200,
        size: "64GB",
        speed: "3200MHz",
        type: "DDR4",
        slotsUsed: 2,
        image: "https://placehold.co/100x100?text=Fury+Beast+64GB  ",
      },

      {
        id: 9,
        name: "Corsair Vengeance RGB 32GB",
        price: 120,
        size: "32GB",
        speed: "3200MHz",
        type: "DDR4",
        slotsUsed: 2,
        image: "https://placehold.co/100x100?text=Vengeance+32GB  ",
      },
      {
        id: 10,
        name: "G.Skill Trident Z5 16GB",
        price: 80,
        size: "16GB",
        speed: "3600MHz",
        type: "DDR5",
        slotsUsed: 2,
        image: "https://placehold.co/100x100?text=Trident+Z5+16GB  ",
      },
      {
        id: 11,
        name: "Crucial Ballistix 32GB",
        price: 110,
        size: "32GB",
        speed: "3000MHz",
        type: "DDR4",
        slotsUsed: 2,
        image: "https://placehold.co/100x100?text=Ballistix+32GB  ",
      },
      {
        id: 12,
        name: "Kingston Fury Beast 64GB",
        price: 200,
        size: "64GB",
        speed: "3200MHz",
        type: "DDR4",
        slotsUsed: 2,
        image: "https://placehold.co/100x100?text=Fury+Beast+64GB  ",
      },

      {
        id: 13,
        name: "Corsair Vengeance RGB 32GB",
        price: 120,
        size: "32GB",
        speed: "3200MHz",
        type: "DDR4",
        slotsUsed: 2,
        image: "https://placehold.co/100x100?text=Vengeance+32GB  ",
      },
      {
        id: 14,
        name: "G.Skill Trident Z5 16GB",
        price: 80,
        size: "16GB",
        speed: "3600MHz",
        type: "DDR5",
        slotsUsed: 2,
        image: "https://placehold.co/100x100?text=Trident+Z5+16GB  ",
      },
      {
        id: 15,
        name: "Crucial Ballistix 32GB",
        price: 110,
        size: "32GB",
        speed: "3000MHz",
        type: "DDR4",
        slotsUsed: 2,
        image: "https://placehold.co/100x100?text=Ballistix+32GB  ",
      },
      {
        id: 16,
        name: "Kingston Fury Beast 64GB",
        price: 200,
        size: "64GB",
        speed: "3200MHz",
        type: "DDR4",
        slotsUsed: 2,
        image: "https://placehold.co/100x100?text=Fury+Beast+64GB  ",
      },

      {
        id: 17,
        name: "Corsair Vengeance RGB 32GB",
        price: 120,
        size: "32GB",
        speed: "3200MHz",
        type: "DDR4",
        slotsUsed: 2,
        image: "https://placehold.co/100x100?text=Vengeance+32GB  ",
      },
      {
        id: 18,
        name: "G.Skill Trident Z5 16GB",
        price: 80,
        size: "16GB",
        speed: "3600MHz",
        type: "DDR5",
        slotsUsed: 2,
        image: "https://placehold.co/100x100?text=Trident+Z5+16GB  ",
      },
      {
        id: 19,
        name: "Crucial Ballistix 32GB",
        price: 110,
        size: "32GB",
        speed: "3000MHz",
        type: "DDR4",
        slotsUsed: 2,
        image: "https://placehold.co/100x100?text=Ballistix+32GB  ",
      },
      {
        id: 20,
        name: "Kingston Fury Beast 64GB",
        price: 200,
        size: "64GB",
        speed: "3200MHz",
        type: "DDR4",
        slotsUsed: 2,
        image: "https://placehold.co/100x100?text=Fury+Beast+64GB  ",
      },
      {
        id: 21,
        name: "Corsair Vengeance RGB 32GB",
        price: 120,
        size: "32GB",
        speed: "3200MHz",
        type: "DDR4",
        slotsUsed: 2,
        image: "https://placehold.co/100x100?text=Vengeance+32GB  ",
      },
      {
        id: 22,
        name: "G.Skill Trident Z5 16GB",
        price: 80,
        size: "16GB",
        speed: "3600MHz",
        type: "DDR5",
        slotsUsed: 2,
        image: "https://placehold.co/100x100?text=Trident+Z5+16GB  ",
      },
      {
        id: 23,
        name: "Crucial Ballistix 32GB",
        price: 110,
        size: "32GB",
        speed: "3000MHz",
        type: "DDR4",
        slotsUsed: 2,
        image: "https://placehold.co/100x100?text=Ballistix+32GB  ",
      },
      {
        id: 24,
        name: "Kingston Fury Beast 64GB",
        price: 200,
        size: "64GB",
        speed: "3200MHz",
        type: "DDR4",
        slotsUsed: 2,
        image: "https://placehold.co/100x100?text=Fury+Beast+64GB  ",
      },
    ],
    "cpu-cooler": [
      {
        id: 1,
        name: "Noctua NH-D15",
        price: 120,
        supportedSockets: ["LGA1700", "AM5", "AM4"],
        maxTDP: 270,
        height: 165,
        image: "https://placehold.co/100x100?text=NH-D15  ",
      },
      {
        id: 2,
        name: "Corsair iCUE H150i ELITE CAPELLIX",
        price: 150,
        supportedSockets: ["LGA1700", "AM5", "AM4"],
        maxTDP: 280,
        height: 294,
        image: "https://placehold.co/100x100?text=H150i+ELITE  ",
      },
      {
        id: 3,
        name: "be quiet! Dark Rock Pro 4",
        price: 90,
        supportedSockets: ["LGA1700", "AM5", "AM4"],
        maxTDP: 250,
        height: 158,
        image: "https://placehold.co/100x100?text=DRP4  ",
      },
      {
        id: 4,
        name: "Arctic Freezer 34 eSports",
        price: 50,
        supportedSockets: ["LGA1700"],
        maxTDP: 150,
        height: 156,
        image: "https://placehold.co/100x100?text=F34+ESports  ",
      },
      // Add more CPU Cooler mock data as needed...
    ],
    storage: [
      {
        id: 1,
        name: "Samsung 980 Pro 1TB",
        price: 100,
        capacity: "1TB",
        type: "SSD",
        interface: "NVMe M.2 2280",
        image: "https://placehold.co/100x100?text=980+Pro+1TB  ",
      },
      {
        id: 2,
        name: "WD Black SN850 2TB",
        price: 200,
        capacity: "2TB",
        type: "SSD",
        interface: "NVMe M.2 2280",
        image: "https://placehold.co/100x100?text=SN850+2TB  ",
      },
      {
        id: 3,
        name: "Seagate Barracuda 4TB",
        price: 80,
        capacity: "4TB",
        type: "HDD",
        interface: 'SATA 3.5"',
        image: "https://placehold.co/100x100?text=Barracuda+4TB  ",
      },
      {
        id: 4,
        name: "Crucial MX500 2TB",
        price: 120,
        capacity: "2TB",
        type: "SSD",
        interface: 'SATA 2.5"',
        image: "https://placehold.co/100x100?text=MX500+2TB  ",
      },
      // Add more Storage mock data as needed...
    ],
    gpu: [
      {
        id: 1,
        name: "RTX 4090",
        price: 1599,
        vram: "24GB",
        length: 310,
        pcieVersion: 4.0,
        image: "https://placehold.co/100x100?text=RTX+4090  ",
      },
      {
        id: 2,
        name: "RTX 4080",
        price: 1199,
        vram: "16GB",
        length: 285,
        pcieVersion: 4.0,
        image: "https://placehold.co/100x100?text=RTX+4080  ",
      },
      {
        id: 3,
        name: "RX 7900 XTX",
        price: 999,
        vram: "24GB",
        length: 283,
        pcieVersion: 4.0,
        image: "https://placehold.co/100x100?text=RX+7900+XTX  ",
      },
      {
        id: 4,
        name: "No Dedicated GPU (Integrated Graphics)",
        price: 0,
        vram: "Depends on CPU",
        length: 0,
        pcieVersion: null,
        image: "https://placehold.co/100x100?text=Integrated+GPU  ",
        isIntegratedOption: true,
      },
      // Add more GPU mock data as needed...
    ],
    psu: [
      {
        id: 1,
        name: "Corsair RM850x",
        price: 150,
        wattage: "850W",
        efficiency: "80+ Gold",
        formFactor: "ATX",
        image: "https://placehold.co/100x100?text=RM850x  ",
      },
      {
        id: 2,
        name: "EVGA SuperNOVA 750W",
        price: 120,
        wattage: "750W",
        efficiency: "80+ Bronze",
        formFactor: "ATX",
        image: "https://placehold.co/100x100?text=SuperNOVA+750W  ",
      },
      {
        id: 3,
        name: "Seasonic Focus GX-650",
        price: 100,
        wattage: "650W",
        efficiency: "80+ Gold",
        formFactor: "ATX",
        image: "https://placehold.co/100x100?text=Focus+GX-650  ",
      },
      // Add more PSU mock data as needed...
    ],
  };

  // Calculate total price based on components and their quantities
  const selectedTotal = Object.entries(buildPcComponents).reduce(
    (sum, [category, component]) => {
      const quantity = quantities[category] || 1; // Default to 1 if no quantity set
      return sum + (component?.price || 0) * quantity;
    },
    0,
  );

  // Get compatible components for the current step (same logic as before)
  const getCurrentStepCompatibleComponents = () => {
    const currentStepId = steps[currentStep]?.id;
    const components = mockComponents[currentStepId] || [];

    switch (currentStepId) {
      case "motherboard":
        const selectedCpuSocket = buildPcComponents.cpu?.socket;
        if (selectedCpuSocket) {
          return components.filter((mb) => mb.socket === selectedCpuSocket);
        }
        return components;

      case "case":
        const selectedMbFormFactor = buildPcComponents.motherboard?.formFactor;
        if (selectedMbFormFactor) {
          return components.filter((c) =>
            c.supportedFormFactors.includes(selectedMbFormFactor)
          );
        }
        return components;

      case "ram":
        const selectedMb = buildPcComponents.motherboard;
        if (selectedMb) {
          const supportedTypes = selectedMb.supportedMemoryTypes || [];
          const maxCapacity = selectedMb.maxMemoryCapacity || Infinity;
          return components.filter((ram) =>
            supportedTypes.includes(ram.type) &&
            parseInt(ram.size) <= maxCapacity
          );
        }
        return components;

      case "cpu-cooler":
        const selectedCpuSocketForCooler = buildPcComponents.cpu?.socket;
        if (selectedCpuSocketForCooler) {
          return components.filter((cooler) =>
            cooler.supportedSockets.includes(selectedCpuSocketForCooler)
          );
        }
        return components;

      case "storage":
        const selectedMbStorageSlots = buildPcComponents.motherboard
          ?.storageSlots;
        if (selectedMbStorageSlots) {
          return components.filter((storage) => {
            if (storage.interface.includes("NVMe M.2")) {
              return selectedMbStorageSlots.m2 > 0;
            } else if (storage.interface.includes("SATA")) {
              return selectedMbStorageSlots.sata > 0;
            }
            return true;
          });
        }
        return components;

      case "gpu":
        const selectedCaseMaxGpuLength = buildPcComponents.case?.maxGpuLength ||
          Infinity;
        const selectedMbPcieVersion =
          buildPcComponents.motherboard?.pcieVersion || 3.0;
        return components.filter((gpu) => {
          if (gpu.isIntegratedOption) {
            if (!buildPcComponents.cpu) return false;
            return buildPcComponents.cpu.integratedGraphics === true;
          }
          if (gpu.length > selectedCaseMaxGpuLength) {
            return false;
          }
          if (gpu.pcieVersion && gpu.pcieVersion > selectedMbPcieVersion) {
            // Allow downgrade for now
          }
          return true;
        });

      // Explicit case for PSU (though default would also work)
      case "psu":
        return components;

      default:
        return components;
    }
  };

  const compatibleComponents = getCurrentStepCompatibleComponents();

  // Pagination Logic (same as before)
  const ITEMS_PER_PAGE = 20;
  const currentStepId = steps[currentStep]?.id;

  const currentPageNumber = currentPage[currentStepId] || 1;

  const startIndex = (currentPageNumber - 1) * ITEMS_PER_PAGE;
  const endIndex = startIndex + ITEMS_PER_PAGE;
  const paginatedComponents = compatibleComponents.slice(startIndex, endIndex);

  const totalPages = Math.ceil(compatibleComponents.length / ITEMS_PER_PAGE);

  const goToPage = (page) => {
    // Validate input page number
    const validatedPage = Math.max(1, Math.min(page, totalPages));
    setCurrentPage((prev) => ({
      ...prev,
      [currentStepId]: validatedPage, // Update page number for the current step
    }));
  };

  const nextPage = () => {
    if (currentPageNumber < totalPages) {
      goToPage(currentPageNumber + 1);
    }
  };

  const prevPage = () => {
    if (currentPageNumber > 1) {
      goToPage(currentPageNumber - 1);
    }
  };

  const renderPageNumbers = () => {
    const pageButtons = [];
    const maxVisiblePages = 5;

    let startPage = Math.max(
      1,
      currentPageNumber - Math.floor(maxVisiblePages / 2),
    );
    let endPage = Math.min(totalPages, startPage + maxVisiblePages - 1);

    // Adjust startPage if the range is too small
    if (endPage - startPage + 1 < maxVisiblePages) {
      startPage = Math.max(1, endPage - maxVisiblePages + 1);
    }

    for (let i = startPage; i <= endPage; i++) {
      pageButtons.push(
        <button
          key={i}
          onClick={() => goToPage(i)}
          className={`btn btn-sm mx-1 ${
            currentPageNumber === i ? "btn-accent" : "btn-secondary btn-outline" // Use accent for current page, secondary outline for others
          }`}
        >
          {i}
        </button>,
      );
    }

    return pageButtons;
  };

  // Handler for quantity changes
  const handleQuantityChange = (category, value) => {
    // Validate input to ensure it's a positive integer
    const numValue = Math.max(1, parseInt(value) || 1);
    setQuantities((prev) => ({
      ...prev,
      [category]: numValue,
    }));
  };

  // Handler to add the entire build to the cart
  const handleAddBuildToCart = () => {
    if (!buildPcComponents || Object.keys(buildPcComponents).length === 0) {
      alert("Your build is empty!");
      return;
    }

    // Iterate through each selected component and add it to the cart
    Object.entries(buildPcComponents).forEach(([category, component]) => {
      if (component) { // Check if component exists
        const quantity = quantities[category] || 1; // Use selected quantity or default to 1
        // Add the component multiple times based on quantity
        for (let i = 0; i < quantity; i++) {
          addToCart({ ...component, quantity: 1 }); // Add individual item to cart
        }
      }
    });

    // Optionally, navigate to the cart page after adding
    // navigate('/cart');
  };

  // Determine if it's the last step
  const isLastStep = currentStep === steps.length - 1;

  return (
    <div className="container mx-auto px-4 py-8 bg-inherit min-h-screen">
      <h1 className="text-3xl font-bold mb-8">Build Your PC</h1>

      {/* Introductory Section - Full Width, Bigger, with Overlay Text */}
      <div className="relative w-full h-96 mb-8 rounded-xl overflow-hidden shadow-xl border border-base-300">
        {/* Adjust h-96 for desired height */}
        <img
          src={BuildGif}
          alt="Building a PC illustration"
          className="w-full h-full object-cover"
        />
        {/* Overlay Text Container */}
        <div className="absolute inset-0 flex flex-col items-center justify-center bg-black/50 p-6">
          {/* bg-black/50 adds semi-transparent dark overlay */}
          <h2 className="text-4xl md:text-5xl font-bold text-white mb-4 text-center">
            {/* Larger text, centered */}
            Build Your Dream PC
          </h2>
          <p className="text-xl text-white/90 mb-6 text-center max-w-2xl">
            {/* Slightly smaller text, centered, limited width */}
            Customize your perfect computer by selecting each component
            step-by-step. Follow the guide to choose compatible parts, configure
            quantities, and finalize your build.
          </p>
          <p className="text-sm text-white/70 text-center">
            {/* Smaller hint text, centered */}
            Need help? Click the information icons next to each step name for
            tips!
          </p>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        {/* Steps Navigation with Information Icon Modals (unchanged) */}
        <div className="lg:col-span-1">
          <div className="card bg-base-100 shadow-lg border border-secondary-content">
            <div className="card-body">
              <h3 className="font-bold text-lg mb-4">Build Progress</h3>
              <div className="steps steps-vertical">
                {steps.map((step, index) => (
                  <div
                    key={step.id}
                    className={`step ${
                      index <= currentStep ? "step-primary" : ""
                    } ${buildPcComponents[step.id] ? "step-success" : ""}`}
                    onClick={() => setCurrentStep(index)}
                  >
                    <div className="flex items-center justify-between">
                      <span>{step.name}</span>
                      <button
                        className="badge badge-sm badge-info text-info-content rounded-full w-5 h-5 flex items-center justify-center text-xs cursor-help ml-1"
                        onClick={(e) => {
                          e.stopPropagation();
                          document.getElementById(`info_modal_${step.id}`)
                            .showModal();
                        }}
                      >
                        i
                      </button>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </div>

        {/* Component Selection */}
        <div className="lg:col-span-2">
          <div className="card bg-base-100 shadow-lg border border-secondary-content">
            <div className="card-body">
              <h2 className="card-title text-2xl mb-6">
                {steps[currentStep]?.title}
              </h2>

              {/* Pagination Controls Above Grid (Always rendered now) */}
              {totalPages > 1 && (
                <div className="flex items-center justify-between mb-4">
                  <button
                    className="btn btn-sm btn-secondary btn-outline" // Changed to secondary outline
                    onClick={prevPage}
                    disabled={currentPageNumber === 1}
                  >
                    Previous
                  </button>
                  <div className="flex items-center">
                    {renderPageNumbers()}
                  </div>
                  <button
                    className="btn btn-sm btn-accent btn-outline" // Changed to secondary outline
                    onClick={nextPage}
                    disabled={currentPageNumber === totalPages}
                  >
                    Next
                  </button>
                </div>
              )}

              {/* Component Grid (Always rendered now) */}
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mb-6">
                {paginatedComponents.map((component) => (
                  <div
                    key={component.id}
                    className={`card bg-base-100 shadow-md rounded-lg border border-secondary-content cursor-pointer transition-all duration-200 ${
                      buildPcComponents[steps[currentStep]?.id]?.id ===
                          component.id
                        ? "bg-primary/10 border-2 border-primary shadow-lg"
                        : "hover:shadow-lg"
                    }`}
                    onClick={() =>
                      setPcComponent(steps[currentStep].id, component)}
                  >
                    <div className="card-body p-4">
                      <div className="flex items-center gap-4">
                        <div className="rounded-md overflow-hidden bg-base-200 p-1">
                          <img
                            src={component.image}
                            alt={component.name}
                            className="w-16 h-16 object-contain rounded-none"
                          />
                        </div>
                        <div className="flex-1 min-w-0">
                          <h3 className="card-title font-bold text-sm truncate">
                            {component.name}
                          </h3>
                          <p className="text-lg font-bold text-primary bg-primary/10 px-2 py-1 rounded inline-block mb-1">
                            DZD {component.price}
                          </p>
                          <div className="text-xs opacity-75 mt-1">
                            {Object.entries(component)
                              .filter(
                                ([key]) =>
                                  ![
                                    "id",
                                    "name",
                                    "price",
                                    "image",
                                    "supportedSockets",
                                    "supportedFormFactors",
                                    "storageSlots",
                                    "isIntegratedOption",
                                    "supportedMemoryTypes",
                                    "maxMemoryCapacity",
                                    "maxMemorySpeed",
                                    "memorySlots",
                                    "maxGpuLength",
                                    "maxCpuCoolerHeight",
                                    "maxTDP",
                                    "interface",
                                    "pcieVersion",
                                    "length",
                                    "tdp",
                                    "slotsUsed",
                                  ].includes(key),
                              )
                              .map(([key, value]) => (
                                <div key={key} className="truncate">
                                  <span className="font-medium capitalize">
                                    {key}:
                                  </span>{" "}
                                  {typeof value === "object"
                                    ? JSON.stringify(value)
                                    : value}
                                </div>
                              ))}
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                ))}
              </div>

              {/* Summary Section (always visible, updated) */}
              <div className="card bg-inherit shadow-inner mt-6 border border-secondary-content">
                <div className="card-body">
                  <h3 className="card-title text-lg">Current Build</h3>
                  <div className="space-y-2">
                    {Object.entries(buildPcComponents).map(
                      ([category, component]) => (
                        <div
                          key={category}
                          className="flex justify-between items-center"
                        >
                          <div className="flex-1">
                            <span className="font-medium text-base-content">
                              {category.toUpperCase()}:
                            </span>
                            <span className="text-sm ml-2">
                              {component?.name}
                            </span>
                          </div>
                          <div className="flex items-center space-x-2">
                            <span className="mr-2">{component.price} DA</span>
                            <input
                              type="number"
                              min="1"
                              value={quantities[category] || 1}
                              onChange={(e) =>
                                handleQuantityChange(category, e.target.value)}
                              className="input input-xs w-20 text-right" // Adjust width as needed
                            />
                          </div>
                        </div>
                      ),
                    )}
                  </div>
                  <div className="divider"></div>
                  <div className="flex justify-between font-bold text-lg">
                    <span>Total:</span>
                    <span className="text-primary">
                      DZD {selectedTotal.toFixed(2)}
                    </span>{" "}
                    {/* Format total */}
                  </div>
                </div>
              </div>

              {/* Navigation Buttons */}
              <div className="flex justify-between mt-4">
                <button
                  className="btn btn-secondary"
                  onClick={() => setCurrentStep(Math.max(0, currentStep - 1))}
                  disabled={currentStep === 0}
                >
                  Previous
                </button>

                {/* Last Step: Replace "Next" with "Add Build to Cart" */}
                {isLastStep
                  ? (
                    <button
                      className="btn btn-primary"
                      onClick={handleAddBuildToCart}
                      disabled={Object.keys(buildPcComponents).length === 0} // Disable if build is empty
                    >
                      Add Build to Cart
                    </button>
                  )
                  : (
                    <button
                      className="btn btn-primary"
                      onClick={() =>
                        setCurrentStep(
                          Math.min(steps.length - 1, currentStep + 1),
                        )}
                      disabled={!buildPcComponents[steps[currentStep]?.id]}
                    >
                      Next
                    </button>
                  )}
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* Modals for Step Information (unchanged) */}
      {steps.map((step) => (
        <dialog
          key={step.id}
          id={`info_modal_${step.id}`}
          className="modal"
        >
          <div className="modal-box max-w-2xl">
            <h3 className="font-bold text-lg mb-2">{step.name} Information</h3>
            <p className="py-2">{stepInfoTexts[step.id]}</p>
            <div className="modal-action">
              <form method="dialog">
                <button className="btn">Close</button>
              </form>
            </div>
          </div>
          <form method="dialog" className="modal-backdrop">
            <button>close</button>
          </form>
        </dialog>
      ))}
    </div>
  );
};

export default BuildPC;
