// src/pages/BuildPC.jsx
import React, { useEffect, useState } from "react";
import { useStore } from "../stores/useStore"; // Assuming useStore manages cart and PC build components
import BuildGif from "../assets/Pc Build .gif";
import { useNavigate } from "react-router-dom";
import { useQuery, useQueryClient } from "@tanstack/react-query"; // Import useQueryClient
import {
  bulkAddToCart,
  fetchCategories,
  searchProducts,
} from "../services/api"; // Import API functions
import { toast } from "sonner"; // Import toast for notifications

const BACKEND_BASE_URL = import.meta.env.VITE_BACKEND_BASE_URL ||
  "http://localhost:8080";
const BuildPC = () => {
  const queryClient = useQueryClient(); // <-- Add this line

  const navigate = useNavigate();
  const [currentStep, setCurrentStep] = useState(0);
  const { buildPcComponents, setPcComponent, cart, addToCart } = useStore(); // Get cart and addToCart from store
  const [quantities, setQuantities] = useState({}); // Local state for quantities

  // State for pagination
  const [currentPage, setCurrentPage] = useState({}); // Use an object to track page per step

  // Tooltips for each step (now used in the modal)
  const stepInfoTexts = {
    cpu:
      "The CPU is the PC’s brain that handles calculations. It must match your motherboard’s CPU socket. Ensure it’s properly cooled for stable performance (use a good CPU cooler).",
    motherboard:
      "The motherboard connects all components in your PC. It must support your CPU’s socket and the right type of RAM. Also, check that the board’s size (ATX, mATX, etc.) fits your case.",
    ram:
      "RAM provides temporary storage for data the CPU needs quick access to. Ensure it's compatible with your motherboard's RAM type (DDR4, DDR5) and speed.",
    case:
      "The case houses all your components. Ensure it's compatible with your motherboard's form factor (ATX, Micro-ATX, etc.) and has enough space for your GPU and PSU.",
    "cooler":
      "A CPU cooler dissipates heat generated by the CPU. Choose one compatible with your CPU socket and fits within your case's clearance limits.",
    storage:
      "Storage devices hold your operating system, programs, and files. Choose between SSDs (faster) and HDDs (larger capacity). Ensure your motherboard has the necessary connections (SATA, M.2).",
    gpu:
      "The GPU processes graphics and video. It's essential for gaming and video editing. Ensure your PSU has enough power and your case has enough space.",
    psu:
      "The PSU supplies power to all components. Choose one with enough wattage for your build and good efficiency ratings (80+ Bronze, Gold, etc.).",
  };

  const steps = [
    { id: "cpu", name: "CPU", title: "Select CPU" },
    { id: "motherboard", name: "Motherboard", title: "Select Motherboard" },
    { id: "ram", name: "RAM", title: "Select RAM" },
    { id: "case", name: "Case", title: "Select Case" },
    { id: "cooler", name: "CPU Cooler", title: "Select CPU Cooler" },
    { id: "storage", name: "Storage", title: "Select Storage" },
    { id: "gpu", name: "GPU", title: "Select GPU" },
    { id: "power-supply", name: "PSU", title: "Select Power Supply" },
  ];

  // --- FETCH CATEGORIES ONCE ---
  const {
    data: categoriesData,
    isLoading: categoriesLoading,
    isError: categoriesError,
    error: categoriesFetchError,
  } = useQuery({
    queryKey: ["categories"],
    queryFn: fetchCategories, // API function to fetch categories
    staleTime: 5 * 60 * 1000, // Consider data fresh for 5 minutes
    cacheTime: 10 * 60 * 1000, // Cache for 10 minutes
    onError: (error) => {
      console.error("Error fetching categories:", error);
      toast.error("Failed to load categories. Please try again later.");
    },
  });

  // Create a mapping from step ID to category ID
  const categoryMap = React.useMemo(() => {
    if (!categoriesData) return {};
    // Example mapping - adjust based on your actual category names/IDs
    const map = {};
    categoriesData.forEach((cat) => {
      // Assuming category names align closely with step IDs or have a known mapping
      // You might need a more robust mapping strategy if names don't match
      const stepId = cat.name.toLowerCase().replace(/\s+/g, "-"); // e.g., "CPU" -> "cpu", "Power Supply" -> "power-supply"
      if (steps.some((step) => step.id === stepId)) {
        map[stepId] = cat.id;
      }
    });
    // Add specific mappings if names don't directly translate
    // map['cpu-cooler'] = 'specific-cooler-category-id';
    return map;
  }, [categoriesData, steps]);

  const currentStepId = steps[currentStep]?.id;
  const currentCategoryId = categoryMap[currentStepId];

  // Determine filters based on previously selected components
  const getFiltersForStep = () => {
    let filters = { category_id: currentCategoryId, limit: 20 }; // Default filter for current category

    // Apply compatibility filters based on previous selections using spec_filter
    switch (currentStepId) {
      case "motherboard":
        if (buildPcComponents.cpu?.spec_highlights?.socket) {
          filters.spec_filter =
            `socket:${buildPcComponents.cpu.spec_highlights.socket}`;
        }
        break;
      case "case":
        if (buildPcComponents.motherboard?.spec_highlights?.form_factor) {
          filters.spec_filter =
            `form_factor:${buildPcComponents.motherboard.spec_highlights.form_factor}`;
        }
        break;
      case "ram":
        if (
          buildPcComponents.motherboard?.spec_highlights?.supported_memory_types
        ) {
          // Assuming backend can handle comma-separated string like "DDR4,DDR5" for a 'type' filter
          // filters.spec_filter = `type:${buildPcComponents.motherboard.spec_highlights.supported_memory_types}`;
        }
        break;
      case "cpu-cooler":
        if (buildPcComponents.cpu?.spec_highlights?.socket) {
          filters.spec_filter =
            `supported_sockets:${buildPcComponents.cpu.spec_highlights.socket}`;
        }
        break;
      case "storage":
        // Could filter based on available SATA/M.2 slots on motherboard if backend supports it
        // Example: filters.spec_filter = `interface:SATA` or `interface:NVMe`;
        break;
      case "gpu":
        if (buildPcComponents.case?.spec_highlights?.max_gpu_length) {
          // Backend might need a specific operator for numeric comparison (e.g., max_gpu_length_lte: 285)
          // For now, let's assume a direct filter if backend supports it or filter client-side later if needed
          // filters.spec_filter = `max_gpu_length_lte:${buildPcComponents.case.spec_highlights.max_gpu_length}`;
          // For now, we'll fetch all GPUs for the category and potentially filter client-side if needed
        }
        // Check integrated graphics option - this is more of a display logic than a backend filter
        break;
      case "psu":
        // Could filter based on total system power draw estimation if backend supports it
        break;
      default:
        break;
    }
    return filters;
  };

  const filters = getFiltersForStep();

  const {
    data: productsData,
    isLoading: productsLoading,
    isError: productsError,
    error: productsFetchError,
    refetch: refetchProducts,
  } = useQuery({
    queryKey: ["products", currentStepId, filters], // Include filters in key
    queryFn: () => searchProducts(filters), // API function to fetch products for category with spec_filter
    enabled: !!currentCategoryId, // Only run query if category ID is known
    staleTime: 2 * 60 * 1000, // Consider data fresh for 2 minutes per step
    cacheTime: 5 * 60 * 1000, // Cache for 5 minutes
    onError: (error) => {
      console.error(`Error fetching products for ${currentStepId}:`, error);
      toast.error(`Failed to load ${currentStepId} options. Please try again.`);
    },
  });

  // Process fetched products for display (pagination)
  const allFetchedProducts = productsData?.data || []; // Assuming API returns {  [...], page, limit, total, total_pages }

  // --- PAGINATION LOGIC ---
  const ITEMS_PER_PAGE = 20; // Keep consistent with query limit if possible
  const currentPageNumber = currentPage[currentStepId] || 1;

  const startIndex = (currentPageNumber - 1) * ITEMS_PER_PAGE;
  const endIndex = startIndex + ITEMS_PER_PAGE;
  const paginatedProducts = allFetchedProducts.slice(startIndex, endIndex);

  const totalPages = Math.ceil(allFetchedProducts.length / ITEMS_PER_PAGE);

  const goToPage = (page) => {
    // Validate input page number
    const validatedPage = Math.max(1, Math.min(page, totalPages));
    setCurrentPage((prev) => ({
      ...prev,
      [currentStepId]: validatedPage, // Update page number for the current step
    }));
  };

  const nextPage = () => {
    if (currentPageNumber < totalPages) {
      goToPage(currentPageNumber + 1);
    }
  };

  const prevPage = () => {
    if (currentPageNumber > 1) {
      goToPage(currentPageNumber - 1);
    }
  };

  const renderPageNumbers = () => {
    const pageButtons = [];
    const maxVisiblePages = 5;

    let startPage = Math.max(
      1,
      currentPageNumber - Math.floor(maxVisiblePages / 2),
    );
    let endPage = Math.min(totalPages, startPage + maxVisiblePages - 1);

    // Adjust startPage if the range is too small
    if (endPage - startPage + 1 < maxVisiblePages) {
      startPage = Math.max(1, endPage - maxVisiblePages + 1);
    }

    for (let i = startPage; i <= endPage; i++) {
      pageButtons.push(
        <button
          key={i}
          onClick={() => goToPage(i)}
          className={`btn btn-sm mx-1 ${
            currentPageNumber === i ? "btn-accent" : "btn-secondary btn-outline" // Use accent for current page, secondary outline for others
          }`}
          disabled={productsLoading} // Disable buttons while loading
        >
          {i}
        </button>,
      );
    }

    return pageButtons;
  };

  // Handler for quantity changes
  const handleQuantityChange = (category, value) => {
    // Validate input to ensure it's a positive integer
    const numValue = Math.max(1, parseInt(value) || 1);
    setQuantities((prev) => ({
      ...prev,
      [category]: numValue,
    }));
  };

  // Handler to add the entire build to the cart
  const handleAddBuildToCart = async () => { // Make function async
    if (!buildPcComponents || Object.keys(buildPcComponents).length === 0) {
      toast.error("Your build is empty!");
      return;
    }

    try {
      // Prepare the payload for bulkAddToCart
      const itemsToAdd = Object.entries(buildPcComponents).map(
        ([category, component]) => {
          if (component) {
            const quantity = quantities[category] || 1; // Use selected quantity or default to 1
            return {
              product_id: component.id, // Use the actual product ID from the fetched component
              quantity: quantity,
            };
          }
          return null; // Shouldn't happen if buildPcComponents is checked, but handle gracefully
        },
      ).filter(Boolean); // Remove any null entries

      if (itemsToAdd.length === 0) {
        toast.error("No valid components to add.");
        return;
      }

      console.log("Bulk adding items:", itemsToAdd); // Debug log

      // Call the bulk API function
      const response = await bulkAddToCart(itemsToAdd);

      console.log("Bulk add response:", response); // Debug log
      toast.success("Build added to cart successfully!");
      // This will cause the useQuery hook in CartContext to refetch the data once.
      await queryClient.invalidateQueries({ queryKey: ["cart"] }); // Invalidate all queries starting with 'cart'

      useStore.getState().clearBuildPcComponents(); // Assuming you have a clear function in your store

      // Navigate to the cart page after successful addition
      navigate("/cart"); // Uncomment if you have a navigate hook from react-router-dom
    } catch (error) {
      console.error("Error adding build to cart:", error);
      // Try to get a user-friendly message from the backend response
      const errorMessage = error?.response?.data?.message || error.message ||
        "Failed to add build to cart. Please try again.";
      toast.error(errorMessage);
    }
  };

  // Determine if it's the last step
  const isLastStep = currentStep === steps.length - 1;

  // Determine if all required steps have a selected component
  const isBuildComplete = steps.every((step) =>
    buildPcComponents[step.id] != null
  );

  // Show loading state if categories are still loading
  if (categoriesLoading) {
    return (
      <div className="container mx-auto px-4 py-8 bg-inherit min-h-screen flex items-center justify-center">
        <span className="loading loading-spinner loading-lg"></span>
      </div>
    );
  }

  // Show error state if categories failed to load
  if (categoriesError) {
    return (
      <div className="container mx-auto px-4 py-8 bg-inherit min-h-screen flex items-center justify-center">
        <div className="text-center">
          <p className="text-xl text-error mb-4">
            Error loading categories:{" "}
            {categoriesFetchError?.message || "An unknown error occurred"}
          </p>
          <button
            className="btn btn-primary"
            onClick={() => window.location.reload()}
          >
            Retry
          </button>
        </div>
      </div>
    );
  }

  // Check if the current step has a valid category mapping
  if (!currentCategoryId) {
    // This might happen if the categoryMap doesn't have an entry for the current step ID
    // You might want to show an error or skip this step, depending on your requirements
    console.warn(`No category ID found for step: ${currentStepId}`);
    // For now, let's render an empty state or a message
    return (
      <div className="container mx-auto px-4 py-8 bg-inherit min-h-screen flex items-center justify-center">
        <div className="text-center">
          <p className="text-xl text-warning mb-4">
            Configuration issue: Category for '{currentStepId}' not found.
          </p>
          <button
            className="btn btn-secondary"
            onClick={() => setCurrentStep(Math.max(0, currentStep - 1))}
          >
            Previous
          </button>
        </div>
      </div>
    );
  }

  return (
    <div className="container mx-auto px-4 py-8 bg-inherit min-h-screen">
      <h1 className="text-3xl font-bold mb-8">Build Your PC</h1>

      {/* Introductory Section - Full Width, Bigger, with Overlay Text */}
      <div className="relative w-full h-96 mb-8 rounded-xl overflow-hidden shadow-xl border border-base-300">
        {/* Adjust h-96 for desired height */}
        <img
          src={BuildGif}
          alt="Building a PC illustration"
          className="w-full h-full object-cover"
        />
        {/* Overlay Text Container */}
        <div className="absolute inset-0 flex flex-col items-center justify-center bg-black/50 p-6">
          {/* bg-black/50 adds semi-transparent dark overlay */}
          <h2 className="text-4xl md:text-5xl font-bold text-white mb-4 text-center">
            {/* Larger text, centered */}
            Build Your Dream PC
          </h2>
          <p className="text-xl text-white/90 mb-6 text-center max-w-2xl">
            {/* Slightly smaller text, centered, limited width */}
            Customize your perfect computer by selecting each component
            step-by-step. Follow the guide to choose compatible parts, configure
            quantities, and finalize your build.
          </p>
          <p className="text-sm text-white/70 text-center">
            {/* Smaller hint text, centered */}
            Need help? Click the information icons next to each step name for
            tips!
          </p>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        {/* Steps Navigation with Information Icon Modals (unchanged) */}
        <div className="lg:col-span-1">
          <div className="card bg-base-100 shadow-lg border border-secondary-content">
            <div className="card-body">
              <h3 className="font-bold text-lg mb-4">Build Progress</h3>
              <div className="steps steps-vertical">
                {steps.map((step, index) => (
                  <div
                    key={step.id}
                    className={`step ${
                      index <= currentStep ? "step-primary" : ""
                    } ${buildPcComponents[step.id] ? "step-success" : ""}`}
                    // onClick={() => setCurrentStep(index)} // <-- REMOVED onClick
                    style={{ cursor: "default" }} // Optional: Change cursor to indicate non-clickability
                  >
                    <div className="flex items-center justify-between">
                      <span>{step.name}</span>
                      <button
                        className="badge badge-sm badge-info text-info-content rounded-full w-5 h-5 flex items-center justify-center text-xs cursor-help ml-1"
                        onClick={(e) => {
                          e.stopPropagation();
                          document.getElementById(`info_modal_${step.id}`)
                            .showModal();
                        }}
                      >
                        i
                      </button>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </div>

        {/* Component Selection */}
        <div className="lg:col-span-2">
          <div className="card bg-base-100 shadow-lg border border-secondary-content">
            <div className="card-body">
              <h2 className="card-title text-2xl mb-6">
                {steps[currentStep]?.title}
              </h2>

              {/* Loading State for Products */}
              {productsLoading && (
                <div className="flex justify-center items-center h-48">
                  <span className="loading loading-spinner loading-lg"></span>
                </div>
              )}

              {/* Error State for Products */}
              {productsError && !productsLoading && (
                <div className="alert alert-error">
                  <p>
                    Error loading {steps[currentStep]?.title} options:{" "}
                    {productsFetchError?.message || "An unknown error occurred"}
                  </p>
                  <button
                    className="btn btn-sm"
                    onClick={() => refetchProducts()}
                  >
                    Retry
                  </button>
                </div>
              )}

              {/* Pagination Controls Above Grid (Always rendered now) */}
              {!productsLoading && !productsError && totalPages > 1 && (
                <div className="flex items-center justify-between mb-4">
                  <button
                    className="btn btn-sm btn-secondary btn-outline" // Changed to secondary outline
                    onClick={prevPage}
                    disabled={currentPageNumber === 1 || productsLoading} // Disable when loading or on first page
                  >
                    Previous
                  </button>
                  <div className="flex items-center">
                    {renderPageNumbers()}
                  </div>
                  <button
                    className="btn btn-sm btn-accent btn-outline" // Changed to secondary outline
                    onClick={nextPage}
                    disabled={currentPageNumber === totalPages ||
                      productsLoading} // Disable when loading or on last page
                  >
                    Next
                  </button>
                </div>
              )}

              {/* Component Grid (Rendered when not loading and no error) */}
              {!productsLoading && !productsError && (
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mb-6">
                  {paginatedProducts.map((component) => (
                    <div
                      key={component.id} // Use the actual product ID
                      className={`card bg-base-100 shadow-md rounded-lg border border-secondary-content cursor-pointer transition-all duration-200 ${
                        buildPcComponents[steps[currentStep]?.id]?.id ===
                            component.id
                          ? "bg-primary/10 border-2 border-primary shadow-lg"
                          : "hover:shadow-lg"
                      }`}
                      onClick={() =>
                        setPcComponent(steps[currentStep].id, component)} // Pass the full component object
                    >
                      <div className="card-body p-4">
                        <div className="flex items-center gap-4">
                          {/* Use the actual image URL from the component */}
                          <div className="rounded-md overflow-hidden bg-base-200 p-1">
                            <img
                              src={component.image_urls &&
                                  component.image_urls.length > 0
                                ? `${
                                  import.meta.env.VITE_BACKEND_BASE_URL ||
                                  "http://localhost:8080"
                                }${component.image_urls[0]}`
                                : "https://placehold.co/100x100?text=No+Image  "} // Fallback placeholder
                              alt={component.name}
                              className="w-16 h-16 object-contain rounded-none"
                            />
                          </div>
                          <div className="flex-1 min-w-0">
                            <h3 className="card-title font-bold text-sm truncate">
                              {component.name}
                            </h3>
                            <p className="text-lg font-bold text-primary bg-primary/10 px-2 py-1 rounded inline-block mb-1">
                              DZD {component.price_cents / 100}{" "}
                              {/* Assuming price is in cents */}
                            </p>
                            {/* Display relevant spec highlights - adjust keys as needed */}
                            <div className="text-xs opacity-75 mt-1">
                              {Object.entries(component.spec_highlights || {})
                                .slice(0, 3).map(([key, value]) => ( // Show first 3 spec highlights
                                  <div key={key} className="truncate">
                                    <span className="font-medium capitalize">
                                      {key}:
                                    </span>{" "}
                                    {typeof value === "object"
                                      ? JSON.stringify(value)
                                      : value}
                                  </div>
                                ))}
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  ))}
                </div>
              )}

              {/* Summary Section (always visible, updated) */}
              <div className="card bg-inherit shadow-inner mt-6 border border-secondary-content">
                <div className="card-body">
                  <h3 className="card-title text-lg">Current Build</h3>
                  <div className="space-y-2">
                    {Object.entries(buildPcComponents).map(
                      ([category, component]) => (
                        <div
                          key={category}
                          className="flex justify-between items-center"
                        >
                          <div className="flex-1">
                            <span className="font-medium text-base-content">
                              {category.toUpperCase()}:
                            </span>
                            <span className="text-sm ml-2">
                              {component?.name}
                            </span>
                          </div>
                          <div className="flex items-center space-x-2">
                            {/* Use price_cents and convert to display format */}
                            <span className="mr-2">
                              {(component?.price_cents / 100).toFixed(2)} DA
                            </span>
                            <input
                              type="number"
                              min="1"
                              value={quantities[category] || 1}
                              onChange={(e) =>
                                handleQuantityChange(category, e.target.value)}
                              className="input input-xs w-20 text-right" // Adjust width as needed
                            />
                          </div>
                        </div>
                      ),
                    )}
                  </div>
                  <div className="divider"></div>
                  {/* Calculate total using price_cents */}
                  <div className="flex justify-between font-bold text-lg">
                    <span>Total:</span>
                    <span className="text-primary">
                      DZD {Object.entries(buildPcComponents).reduce(
                        (sum, [category, component]) => {
                          const quantity = quantities[category] || 1;
                          return sum +
                            ((component?.price_cents || 0) / 100) * quantity;
                        },
                        0,
                      ).toFixed(2)}
                    </span>
                  </div>
                </div>
              </div>

              {/* Navigation Buttons */}
              <div className="flex justify-between mt-4">
                <button
                  className="btn btn-secondary"
                  onClick={() => setCurrentStep(Math.max(0, currentStep - 1))}
                  disabled={currentStep === 0}
                >
                  Previous
                </button>

                {/* Last Step: Replace "Next" with "Add Build to Cart" */}
                {isLastStep
                  ? (
                    <button
                      className="btn btn-primary"
                      onClick={handleAddBuildToCart}
                      disabled={!isBuildComplete || productsLoading} // Disable if build is incomplete or loading
                    >
                      Add Build to Cart
                    </button>
                  )
                  : (
                    <button
                      className="btn btn-primary"
                      onClick={() =>
                        setCurrentStep(
                          Math.min(steps.length - 1, currentStep + 1),
                        )}
                      disabled={!buildPcComponents[steps[currentStep]?.id] ||
                        productsLoading} // Disable if no selection for current step or loading
                    >
                      Next
                    </button>
                  )}
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* Modals for Step Information (unchanged) */}
      {steps.map((step) => (
        <dialog
          key={step.id}
          id={`info_modal_${step.id}`}
          className="modal"
        >
          <div className="modal-box max-w-2xl">
            <h3 className="font-bold text-lg mb-2">{step.name} Information</h3>
            <p className="py-2">{stepInfoTexts[step.id]}</p>
            <div className="modal-action">
              <form method="dialog">
                <button className="btn">Close</button>
              </form>
            </div>
          </div>
          <form method="dialog" className="modal-backdrop">
            <button>close</button>
          </form>
        </dialog>
      ))}
    </div>
  );
};

export default BuildPC;
